---
- name: Configure EC2 instances
  hosts: all
  become: true
  vars:
    app_directory: /home/bun/bun-htmx-4640
    service_file_name: bun-4640-project.service

  tasks:
    - name: Install required packages (curl, unzip)
      apt:
        name:
          - curl
          - unzip
        state: present
        update_cache: yes

    - name: Create bun user
      user:
        name: bun
        shell: /bin/bash
        home: /home/bun
        group: sudo
        createhome: yes
        state: present

    - name: Install bun runtime
      become_user: bun
      shell: curl -fsSL https://bun.sh/install | sudo -u bun bash
      args:
        creates: /home/bun/.bun/bin/bun

    - name: Install Caddy web server following official instructions
      become: true
      shell: |
        sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https curl
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
        sudo apt update
        sudo apt install caddy
      args:
        creates: /usr/bin/caddy

    - name: Create app directory
      file:
        path: "{{ app_directory }}"
        state: directory
        owner: bun
        group: bun
        mode: "0755"

    - name: Transfer application files
      copy:
        src: "{{ item }}"
        dest: "{{ app_directory }}"
        owner: bun
        group: bun
        mode: "0644"
      loop: "{{ lookup('fileglob', './4640-assignment-app-files/bun-htmx-4640/*', wantlist=True) }}"

    - name: Transfer service file
      copy:
        src: "./4640-assignment-app-files/{{ service_file_name }}"
        dest: "/etc/systemd/system/{{ service_file_name }}"
        owner: root
        group: root
        mode: "0644"
      notify: restart "{{ service_file_name}}"

    - name: Replace default Caddyfile
      copy:
        src: ./4640-assignment-app-files/Caddyfile
        dest: /etc/caddy/Caddyfile
        owner: root
        group: root
        mode: "0644"
      notify: restart caddy

  handlers:
    - name: restart "{{ service_file_name }}"
      systemd:
        name: "{{ service_file_name }}"
        state: restarted

    - name: restart caddy
      systemd:
        name: caddy
        state: restarted
